### PR TITLE
Added -where: method accepting raw NSPredicate, minor cleanup

### PR DESCRIPTION
**Pull request by nickynick**

### CODE REVIEW

**Comment by apparentsoft** [comment]
Why did you "Replace instancetype with RACSignal\* in method return types"?

**Comment by nickynick** [comment]
As I understand it, `instancetype` indicates that the returned value is of the same type as the receiver. Which is not really true in our case, because we always return signals no matter what. Say, even if you call one of these methods on `RACSubject`, you still get a `RACSignal`. 

Actually, there is an example from ReactiveCocoa. In `RACSignal.h` you can see redefined methods from `RACStream`: `- (instancetype)concat:(RACStream *)stream;` is redefined as `- (RACSignal *)concat:(RACSignal *)signal;` and so on.

**Comment by apparentsoft** [comment]
You understand `instancetype` correctly. While I agree now that in `saveContext` I return `RACSignal *` directly, in most other methods I just process the stream with RACStream \* operations, which return `instancetype` themselves.

**Comment by nickynick** [comment]
If this was a `RACStream` category, then the correct return type would indeed be `instancetype`. But this is the category on `RACSignal`, and, as I pointed out before, all `RACSignal`'s implementations of `RACStream` operations have return types explicitly redefined as `RACSignal *`.

**Comment by apparentsoft** [comment]
I see. The question, then should these methods be moved to a category of RACStream or should the return type be an explicit RACSignal, as you suggested. What do you think are the pros and cons of each approach?

**Comment by nickynick** [comment]
Well, I think the whole thing doesn't make much sense for `RACStream`s or `RACSequence`s. After all, the starting point is usually `+ (RACSignal *)findAll;` or `+ (RACSignal *)findOne;`. So I'd suggest to leave it as a `RACSignal` category and have methods return signals as well.

**Comment by apparentsoft** [comment]
That's what I thought as well, following your previous reasoning. Thanks for noticing this and making the change.

**Pull request merged**
